app_name: follower
app_version: 1.0.0
app_addr: :1234
author: lts
env: dev
database:
  - driver: mysql
    host: 127.0.0.1
    port: 3306
    database: follower
    username: root
    password: root
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
    prefix: ""
redis:
  - host: 127.0.0.1
    port: 6379
    password: ""
log_host: 127.0.0.1
log_port: 544